# Generated by Django 2.1.5 on 2019-12-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='error_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='fps',
            field=models.IntegerField(null=True),
        ),
    ]
